In [2]:
import os 
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [3]:
curpath=os.getcwd()
curpath

'C:\\Users\\gg664\\AppData\\Local\\Programs\\Python\\Python38\\Scripts\\시각화프로젝트\\영화데이터분석'

In [4]:
#data 폴더로 작업경로를 변경합니다. (상대경로 사용)
os.chdir(path = './csvdata')
curpath=os.getcwd()
curpath

'C:\\Users\\gg664\\AppData\\Local\\Programs\\Python\\Python38\\Scripts\\시각화프로젝트\\영화데이터분석\\csvdata'

In [5]:
os.listdir()

['KOBIS_지역별_점유율_2020-08-16~2020-08-22.csv',
 'KOBIS_지역별_점유율_2020-08-23~2020-08-29.csv',
 'KOBIS_지역별_점유율_2020-08-30~2020-09-05.csv',
 'KOBIS_지역별_점유율_2020-09-06~2020-09-12.csv',
 'KOBIS_지역별_점유율_2020-09-13~2020-09-19.csv',
 'KOBIS_지역별_점유율_2020-09-20~2020-09-26.csv',
 'KOBIS_지역별_점유율_2020-09-27~2020-10-03.csv',
 'KOBIS_지역별_점유율_2020-10-04~2020-10-10.csv',
 'KOBIS_지역별_점유율_2020-10-11~2020-10-17.csv',
 'KOBIS_지역별_점유율_2020-10-18~2020-10-24.csv',
 'KOBIS_지역별_점유율_2020-10-25~2020-10-31.csv',
 'KOBIS_지역별_점유율_2020-11-01~2020-11-07.csv',
 'KOBIS_지역별_점유율_2020-11-08~2020-11-14.csv',
 'KOBIS_지역별_점유율_2020-11-15~2020-11-21.csv',
 'KOBIS_지역별_점유율_2020-11-22~2020-11-28.csv',
 'KOBIS_지역별_점유율_2020-11-29~2020-12-05.csv',
 'KOBIS_지역별_점유율_2020-12-06~2020-12-12.csv',
 'KOBIS_지역별_점유율_2020-12-13~2020-12-19.csv',
 'KOBIS_지역별_점유율_2020-12-20~2020-12-26.csv',
 'KOBIS_지역별_점유율_2020-12-27~2020-12-31.csv']

In [12]:
sdate_range=pd.date_range('2020-08-16','2020-12-26',freq = '7D') #real : 2020-12-26
sdate_range=pd.Series(sdate_range.format())
#list(sdate_range)

edate_range=pd.date_range('2020-08-22','2020-12-31',freq = '7D') #real :   2020-12-31
edate_range=pd.Series(edate_range.format())
#list(edate_range)

date_range = list(zip(sdate_range,edate_range))
#date_range

# 추가작업
date_range.append(('2020-12-27','2020-12-31'))
date_range

[('2020-08-16', '2020-08-22'),
 ('2020-08-23', '2020-08-29'),
 ('2020-08-30', '2020-09-05'),
 ('2020-09-06', '2020-09-12'),
 ('2020-09-13', '2020-09-19'),
 ('2020-09-20', '2020-09-26'),
 ('2020-09-27', '2020-10-03'),
 ('2020-10-04', '2020-10-10'),
 ('2020-10-11', '2020-10-17'),
 ('2020-10-18', '2020-10-24'),
 ('2020-10-25', '2020-10-31'),
 ('2020-11-01', '2020-11-07'),
 ('2020-11-08', '2020-11-14'),
 ('2020-11-15', '2020-11-21'),
 ('2020-11-22', '2020-11-28'),
 ('2020-11-29', '2020-12-05'),
 ('2020-12-06', '2020-12-12'),
 ('2020-12-13', '2020-12-19'),
 ('2020-12-20', '2020-12-26'),
 ('2020-12-27', '2020-12-31')]

In [86]:
## 초기화
seoul_movie=pd.DataFrame()
busan_movie=pd.DataFrame()

In [87]:
for date in date_range:
    
    date_index = date[0]+"~"+date[1]
    filename = "KOBIS_지역별_점유율_"+date_index+".csv"

    movie1 = pd.read_csv(filename, encoding='UTF-8')
    #movie1

    movie1.dropna(inplace=True)
    movie1 = movie1.loc[[5,7],['■ 지역별 점유율','Unnamed: 10','Unnamed: 11']]
    movie1.rename({'■ 지역별 점유율':'지역','Unnamed: 10':'매출액','Unnamed: 11':'관객수'},axis='columns',inplace=True)
    movie1['기간']=date_index

    seoul_movie = pd.concat([seoul_movie,movie1[movie1['지역'] == '서울시']])
    busan_movie = pd.concat([busan_movie,movie1[movie1['지역'] == '부산시']])

In [96]:
seoul_movie.set_index('기간',inplace=True)
seoul_movie

                        지역            매출액      관객수
기간
2020-08-16~2020-08-22  서울시  3,361,656,490  368,804
2020-08-23~2020-08-29  서울시  2,189,550,260  247,399
2020-08-30~2020-09-05  서울시  1,842,116,650  200,100
2020-09-06~2020-09-12  서울시  1,733,144,880  188,395
2020-09-13~2020-09-19  서울시  1,571,785,690  172,993
2020-09-20~2020-09-26  서울시  1,686,750,342  194,747
2020-10-04~2020-10-10  서울시  2,310,220,710  243,950
2020-10-11~2020-10-17  서울시  1,635,498,260  175,172
2020-10-18~2020-10-24  서울시  2,051,049,940  235,614
2020-10-25~2020-10-31  서울시  2,345,716,060  266,763
2020-11-01~2020-11-07  서울시  2,686,707,390  290,238
2020-11-08~2020-11-14  서울시  2,595,964,430  284,599
2020-11-15~2020-11-21  서울시  2,087,858,250  229,587
2020-11-22~2020-11-28  서울시  1,340,672,930  155,879
2020-11-29~2020-12-05  서울시    978,608,420  116,440
2020-12-06~2020-12-12  서울시    752,040,660   87,820
2020-12-13~2020-12-19  서울시    606,209,800   71,087
2020-12-20~2020-12-26  서울시  1,249,933,430  141,279
2020-12-27~2020-12-31  서울시    754,663,270   91,153

In [97]:
busan_movie.set_index('기간',inplace=True)
busan_movie

                        지역            매출액      관객수
기간
2020-08-16~2020-08-22  부산시  1,114,537,230  123,943
2020-08-23~2020-08-29  부산시    618,924,290   71,890
2020-08-30~2020-09-05  부산시    467,448,880   53,630
2020-09-06~2020-09-12  부산시    401,747,560   45,878
2020-09-13~2020-09-19  부산시    350,543,860   40,374
2020-09-20~2020-09-26  부산시    369,444,420   43,470
2020-09-27~2020-10-03  부산시  1,270,147,320  137,503
2020-10-04~2020-10-10  부산시    677,889,690   74,197
2020-10-11~2020-10-17  부산시    425,792,690   46,497
2020-10-18~2020-10-24  부산시    517,480,560   57,976
2020-10-25~2020-10-31  부산시    610,113,200   72,140
2020-11-01~2020-11-07  부산시    714,585,170   80,006
2020-11-08~2020-11-14  부산시    709,390,750   79,471
2020-11-15~2020-11-21  부산시    615,709,150   70,033
2020-11-22~2020-11-28  부산시    418,791,390   49,512
2020-11-29~2020-12-05  부산시    231,147,290   27,151
2020-12-06~2020-12-12  부산시    179,772,960   20,889
2020-12-13~2020-12-19  부산시    137,530,150   16,161
2020-12-20~2020-12-26  부산시    263,412,500   30,494
2020-12-27~2020-12-31  부산시    162,778,220   20,138

In [100]:
seoul_movie.to_csv("../result_2020/seoul_movie_2020.csv",encoding="utf-8-sig")
busan_movie.to_csv("../result_2020/busan_movie_2020.csv",encoding="utf-8-sig")